name: Parallel_Workflow
on: push
runs-on: ubuntu-latest
jobs:
  first-job:
    steps: 
      - name: Printing Statement1
        run: echo "Hello GitHub Actions!"
      - name: Printing Statement2
        run: echo "Good Morning!"
  second-job:
    steps: 
      - name: Printing Statement3
        run: echo "Today I'm larning GitHub-Actions"
      - name: Printing Statement4
        run: echo "All is not Well"
